name: Fluid Attacks - Paso 2

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run SAST
        uses: fluidattacks/skims-action@v1
        continue-on-error: true
        with:
          config: fluidattacks/config.yaml

      - name: Run SCA
        uses: fluidattacks/sifts-action@v1
        continue-on-error: true
        with:
          config: fluidattacks/config.yaml

      - name: Run Secrets
        uses: fluidattacks/matches-action@v1
        continue-on-error: true
        with:
          config: fluidattacks/config.yaml